const pastas = {
	Imagem: [
		".png",
		".jpg",
		".jpeg",
		".svg",
		".xcf",
		".gif",
		".bmp",
		".tiff",
		".webp",
	],
	Documento: [".txt", ".pdf", ".doc", ".docx", ".odt", ".rtf", ".xml"],
	Planilha: [".xls", ".xlsx", ".ods", ".csv"],
	Vídeo: [".mp4", ".webm", ".avi", ".mov", ".wmv", ".mkv"],
	Código: [
		".json",
		".php",
		".js",
		".html",
		".css",
		".py",
		".java",
		".cpp",
		".c",
	],
	Instalador: [".exe", ".msi", ".dmg", ".deb", ".rpm"],
	Fonte: [".ttf", ".woff", ".otf"],
	Áudio: [".mp3", ".wav", ".ogg", ".flac", ".aac", ".m4a"],
	Apresentação: [".ppt", ".pptx", ".key"],
	Compactado: [".bak", ".zip", ".tar", ".gz", ".7z"],
	"Banco de dados": [".sql", ".sqlite", ".db", ".mdb", ".accdb"],
	"e-book": [".epub", ".mobi"],
	Firmware: [".bin", ".hex"],
	"Imagem de disco": [".iso", ".img"],
	Minecraft: [".mcpack"],
};

module.exports = { pastas };
